from .job_prompts import JOB_ENHANCEMENT_SYSTEM_PROMPT, JOB_ENHANCEMENT_USER_PROMPT
from .cv_evaluator_prompt import CV_EVALUATOR_SYSTEM_PROMPT, CV_EVALUATOR_USER_PROMPT
from .question_generator_prompt import (
    TECHNICAL_QUESTION_GENERATING_SYSTEM_PROMPT,
    BEHAVIORAL_QUESTION_GENERATING_SYSTEM_PROMPT,
    GAP_QUESTION_GENERATING_SYSTEM_PROMPT,
    QUESTION_GENERATING_USER_PROMPT
)